version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres_part2-5
    environment:
      POSTGRES_DB: part2-5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

